version: '3.2'

services:
  watchtower:
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  trx-api:
    image: sebastianmontero/${DOCKER_IMAGE_NAME}:latest
    volumes:
      - ${BWS_CREDENTIALS_HOST_DIR}:/bws-credentials
    labels:
      - "com.centurylinklabs.watchtower.enable=true"